import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/theme";

const font = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${font.className}`}
    >
      {/* Anti-FOUC: apply .dark before React hydration */}
      <head>
        {/* <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('theme');var mq=window.matchMedia('(prefers-color-scheme: dark)').matches;if(t==='dark'||(t===null||t==='system')&&mq){document.documentElement.classList.add('dark')}}catch(e){}})()`,
          }}
        /> */}
      </head>
      <body className="min-h-full flex flex-col bg-white dark:bg-gray-950 transition-colors duration-200">
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
